### ISSUE TITLE
Not setting frequency on Windows

### ISSUE THREAD

**Issue by dtc2344** [th0ma5w/rtl_fm_python#4]
I have compiled it on windows but it wont set any frequency i give it

[code].\rtl_fm_python -M wbfm -f 101.5M | play -r 32k -t raw -e s -b 16 -c 1 -V1-[/code]

I'm using Sox on windows i just renamed sox.exe to play.exe and put it on the path

[IMG]http://i62.tinypic.com/6zrok5.jpg[/IMG]

[IMG]http://i62.tinypic.com/30wsghk.png[/IMG]

It always sets the frequency to 271000 and there is no sound

if i use rtl_fm normally it works and i can hear sound

**Comment by th0ma5w** [comment]
Here's a guess that I'd like you to try if possible. In rtl_fm_python.c there is code that looks like this:

#ifndef _WIN32
sigact.sa_handler = sighandler;
sigemptyset(&sigact.sa_mask);
sigact.sa_flags = 0;

However, the "ifndef" is indented. According to http://stackoverflow.com/questions/2975330/how-do-you-indent-preprocessor-statements it might be that the optional directive here cannot be indented. Although it may not matter. Try removing the tabs or spaces in front of that first line, so that the # is in the first column, recompile, and see if it helps.

I will try to find a windows installation and recreate this, but some other things to possibly try are to explicitly set the sample rate but really if rtl_fm works this should work? It is also possible that pipe handling of Python on windows may differ in ways I don't fully understand, but this also doesn't seem the case.

I suspect what is really going on is that I'm a poor C programmer, and either the code is handling Win32 in a way I haven't accounted for, or the build process that cmake or other tools use on Win32 need flags that my simple compile script doesn't provide. There may also be an assumption of 64 vs 32 bit that this build process is missing. 

I will keep investigating. I will take a look at the cmake process on windows and see what I can find. Thank you so much for submitting this! Any other details like python version (windows native vs Cygwin or MinGW ) compiler used, and if you're on 32 or 64 bit could be helpful. Thanks again!

**Comment by dtc2344** [comment]
Sorry i forgot to mention

I'm running windows 7 x86 and using MinGW gcc (i686-win32-dwarf-rev1, Built by MinGW-W64 project) 4.9.1 and python 2.7.8 Flask Version: 0.10.1

Command line:
gcc -I .\lib\libusbx\include\libusbx-1.0 -I .\lib\rtl-sdr\include -I .\convenience -I .\getopt -shared -Wl,--out-implib,.\build\rtl_fm_python.lib -o .\build\rtl_fm_python.dll rtl_fm_python.c convenience\convenience.c getopt\getopt.c -L .\lib\pthreads-w32-2-9-1-release\Pre-built.2\dll\x86 -L .\lib\rtl-sdr\build\src -l librtlsdr -lpthreadVC2

I don't know much about c or c++ either just the basics i changed the tabs and recompiled and tested without any success it could be a problem with how i'm compiling it from above do i need to add any other flags while compiling?

Thanks

**Comment by th0ma5w** [comment]
So some more ideas... Without the web browser open, does it initially tune in the station you're looking for? I guess I'm trying to isolate if the initialization parts don't even work, or if it is only when the routines I've added that do the frequency manipulation that are screwing up things.

**Comment by dtc2344** [comment]
The initial frequency was not set the ppm is does get set correctly so i think its just setting frequencies

i created debug strings in lib_set_frequency with in rtl_fm_python.c to show me the current frequency and the new frequency before and after i change frequency

Frequency i entered via the web browser
[DEBUG] lib_set_frequency freqselected (101500000)

Before
[DEBUG] lib_set_frequency oldfreq (0)

After
[DEBUG] lib_set_frequency newfreq (0)

The frequency is not being set in the code the bug is probably somewhere with in rtl_fm_python.c

**Comment by th0ma5w** [comment]
I created a version here that debugs what the parsed frequency value is from the command line, can you give it a go? https://gist.github.com/th0ma5w/b377af69c6362c6e2918

Your debugging seems to tell me however that perhaps ctypes can't send the proper value over anyway :/ I'm still trying to scrounge up a Windows environment, but I may not be able to.

**Comment by dtc2344** [comment]
ok i tried the code you gave me it shows the right frequency

rtl_fm_python_web.py -M wbfm -f 101.5M -
DEBUG Parsed Frequency: 101500000
Found 1 device(s):
- Running on http://0.0.0.0:10100/
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to automatic.
[R82XX] PLL not locked!
Tuned to 271000 Hz.
Oversampling input by: 6x.
Oversampling output by: 1x.
Buffer size: 8.03ms
Exact sample rate is: 1020000.026345 Hz
Sampling at 1020000 S/s.
Output at 170000 Hz.

**Comment by th0ma5w** [comment]
Yeah so what is really weird is then the lines below:
[R82XX] PLL not locked!
Tuned to 271000 Hz.

That is coming I believe from librtlsdr ... So, here's my thinking, and this is a little abstract: I'm not sure if you compiled librtlsdr (and rtlfm) or if you have a binary installation, but I would venture a guess that if you were to compile rtl_fm.c with a build process too similar to how this python ctypes library is being built, that it may exhibit similar behavior. So about some of these code blocks, I'm mostly completely cut & pasting rtl_fm ... and beyond that point where this debug message is printed, the actual value of the frequency that is being tuned should not be manipulated by anything I wrote or even cut & pasted, until the web calls and such, but the very first message then from librtlsdr, namely the center frequency it was passed, is from the start incorrect.

So I'm sort of baffled as to how this could happen unless there is something in the build process, but I simply don't know enough to know what. 

Another thing to try, is to use the rtl_fm_python_thread.py which I guess I haven't documented well enough, but it is essentially all the same stuff just without any web stuff at all, and should just be a loading of rtl_fm as a library from Python.

Just to double check in the common file, you change the line then from:

fm  = ctypes.CDLL('./rtl_fm_python.so')

to

fm  = ctypes.CDLL('./rtl_fm_python.dll')

?

Anyway, to use the thread thing it is just the same, so maybe something like:
.\rtl_fm_python_thread.py -M wbfm -f 101.5M | play -r 32k -t raw -e s -b 16 -c 1 -V1-

Or maybe even:

python .\rtl_fm_python_thread.py -M wbfm -f 101.5M | play -r 32k -t raw -e s -b 16 -c 1 -V1-

Anyway, I suspect it may well behave the same, unfortunately, but it could point to some other clues about what is going on.

My current best theory is that something is happening within rtl_fm.c or the librtlsdr, specifically the sections around #ifndef _WIN32 conditional blocks that is preventing this codebase here from correctly setting the frequency, and this could even be a type mismatch with how the build process sees unsigned 32 bit integers. If that is empty or wrong or null or something, then librtlsdr falls back to this nonsensical number that is out of range. I'm not even sure where 271000 is coming from, or what the significance of that number is really... it doesn't appear anywhere in the librtlsdr source either that I can find, and it doesn't seem like it is the max value or some kind of fall back value of incorrect integer types either like is listed https://en.wikipedia.org/wiki/Integer_(computer_science) ... Oh well, this all serves me right for not having learned all of this stuff, heh, but try the couple things above and see how it does.

**Comment by dtc2344** [comment]
I have tried rtm_fm_python_thread.py

C:\Users\Danny\Desktop\rtl_fm_python>rtl_fm_python_thread.py -M wbfm -f 101.5M |
play -r 32k -t raw -e s -b 16 -c 1 -V1 -

-: (raw)

  Encoding: Signed PCM
  Channels: 1 @ 16-bit
Samplerate: 32000Hz
Replaygain: off
  Duration: unknown

In:0.00% 00:00:00.00 [00:00:00.00] Out:0     [      |      ]        Clip:0
Done.

I already changed ctypes.cdll to rtl_fm_python.dll i'm building the dll into a build folder which i load from there .\build\rtl_fm_python.dll so every build i don't need to keep moving the dll

I have built rtl-sdr from the source without any problems.

So there must be something i'm missing from the build process that win32 needs but linux provides, because we know that rtl-sdr works on both windows and linux and this works on linux but not windows (atleast for me) there must be someone else who has tried this on windows i would like to know if they got it working or not.

I'll take a look at the makefile for rtl-sdr to see how it is building the source and what flags it provides to see if i'm missing something.

Thanks

**Comment by th0ma5w** [comment]
I updated the gist with even more debug statements: https://gist.github.com/th0ma5w/b377af69c6362c6e2918

In rtl_fm.c the controller is defined as "struct controller_state controller;" fairly early on, but perhaps the initial value of freq_now is not being set to 0? I just don't know. Hopefully these debug statements will shed a little more light? Sorry to make you my debugger :P

**Comment by dtc2344** [comment]
It's not a problem i just really want this work. Here is the new output

C:\Users\Danny\Desktop\rtl_fm_python>rtl_fm_python_web.py -M wbfm -f 101.5M | pl
ay -r 32k -t raw -e s -b 16 -c 1 -V1 -

-: (raw)

  Encoding: Signed PCM
  Channels: 1 @ 16-bit
Samplerate: 32000Hz
Replaygain: off
  Duration: unknown

In:0.00% 00:00:00.00 [00:00:00.00] Out:0     [      |      ]        Clip:0    Fo
und 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
DEBUG Final Set Frequency: 101500000
DEBUG Frequency at open: 101500000
- Running on http://0.0.0.0:10100/
  Found Rafael Micro R820T tuner
  DEBUG Frequency at main loop: 101500000
  Tuner gain set to automatic.
  [R82XX] PLL not locked!
  Tuned to 271000 Hz.
  Oversampling input by: 6x.
  Oversampling output by: 1x.
  Buffer size: 8.03ms
  Exact sample rate is: 1020000.026345 Hz
  Sampling at 1020000 S/s.
  Output at 170000 Hz.
  In:0.00% 00:00:00.00 [00:00:00.00] Out:0     [      |      ]        Clip:0
  Aborted.

C:\Users\Danny\Desktop\rtl_fm_python>

This is really weird its like as if it just does not want to tune to anything for comparison here is output of rtl_fm with the same parameters

C:\Users\Danny\Desktop\rtl_fm_python>rtl_fm -M wbfm -f 101.5M | play -r 32k -t r
aw -e s -b 16 -c 1 -V1 -
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM

-: (raw)

  Encoding: Signed PCM
  Channels: 1 @ 16-bit
Samplerate: 32000Hz
Replaygain: off
  Duration: unknown

In:0.00% 00:00:00.00 [00:00:00.00] Out:0     [      |      ]        Clip:0    Fo
und Rafael Micro R820T tuner
Tuner gain set to automatic.
Tuned to 101771000 Hz.
Oversampling input by: 6x.
Oversampling output by: 1x.
Buffer size: 8.03ms
Exact sample rate is: 1020000.026345 Hz
Sampling at 1020000 S/s.
Output at 170000 Hz.
In:0.00% 00:00:02.30 [00:00:00.00] Out:65.5k [   ===|===   ]        Clip:0    Si
gnal caught, exiting!

User cancel, exiting...
In:0.00% 00:00:02.46 [00:00:00.00] Out:73.7k [   ===|===   ]        Clip:0
Aborted.

C:\Users\Danny\Desktop\rtl_fm_python>

**Comment by th0ma5w** [comment]
well you could maybe try adding similar printf statements to the rtl_fm.c source that is in this distribution, or now that i think about that, try copying the rtl_fm.c from your successful build in case it is a different version (although i think i have the latest here?) anyway... more things to try. I wish you luck, and sorry I don't have more information at this time.

**Comment by dtc2344** [comment]
Sorry I have been a bit busy i haven't had much time to try to resolve the problem.

I have glanced through both rtl_fm.c i didn't notice any differences i think they are both the same files, 
i'm not sure what else could be causing this problem i don't know if this is a problem with all windows machines or just for me until someone else can reply here if it worked for them or not.

**Comment by th0ma5w** [comment]
So I managed to get this working on Windows, but I got it working with Cygwin (32-bit).

I followed the following steps:
1. Installed libusb, python dev dependencies via cygwin setup
2. downloaded and install librtlsdr (i had set environment CMAKE_LEGACY_CYGWIN_WIN32=1 )
3. I used the following build.sh:

gcc -L/usr/local/bin/ -I /usr/include/libusb-1.0 -I ./convenience/ -I ./getopt -shared -Wl,-soname,rtl_fm_python -o rtl_fm_python.so -fPIC rtl_fm_python.c convenience/convenience.c getopt/getopt.c -lcygrtlsdr-0
1. I used the following command line (although I should've set a PPM heh)

./rtl_fm_python_web.py -M wbfm -f 101.1M - | play -r 32k -t raw -e s -b 16 -c 1 -V1 -

... and it seemed to work. One thing that occurred to me in doing all of this was 64 vs 32 bit... I'm not sure what is right, but if there is any way to try and force 32-bit in all of your building, that could explain a lot, especially with regards to integer support.

**Comment by th0ma5w** [comment]
Also forgot to add that I had previously done the whole windows libusb driver thing, like for instance to get SDR# working, so that's like before step 1 above.

**Comment by dtc2344** [comment]
Finally after many hours of errors i finally got it working with cygwin. I removed minGW and cygwin, rtlsdr and reinstalled only cygwin and the dependencies.

I compiled rtlsdr with autoreconf and make i couldn't get it to compile with cmake it was giving me errors when compiling adsb.exe then i had to link libusb and rtlsdr.a then copy over the python dependencies Flask etc.

i have to specify "python rtl_fm_python_web.py ..." otherwise it doesn't work it.

The problem is partially solved i still couldn't get it compile without cygwin but it works now so ill leave it as that you can mark as solved or leave open for other people to reply with a solution to compile without cygwin.

Thanks for all your help :)

**Comment by th0ma5w** [comment]
Hey that's great! Sorry such a pain, and I wish I knew more about all of this such as to make it work the way you had it. I'm glad it doesn't seem something fundamental about Windows. 

I need to put up a wiki page perhaps, or just add a note on the readme file referencing this issue because someone may bump into it or also have more insight. I certainly appreciate your patience and checking out the software even. Best of luck in your exploration!!
