### ISSUE TITLE
Does you program support sqelch parametrs?

### ISSUE THREAD

**Issue by kovalroma** [th0ma5w/rtl_fm_python#6]
If I want to listen aircraft traffic, sqelch level is necessary function. 
Does you program support it?

**Comment by th0ma5w** [comment]
Squelch is working either through command line arguments in the start script, or via the API. There is not currently an option in the web GUI but I'm playing around with that. The latest version of rtl-fm seems to reset the value of the squelch level in memory so I'm studying that to find where I'm misunderstanding things.

If you want to, say, scan the air band try nosing around the rtl-fm documentation on the web. You'll also want to skip ATIS frequencies in your area possibly. Has setting squelch worked for your use case in other software?

**Comment by th0ma5w** [comment]
Let me know if the squelch options worked for you.
