### ISSUE TITLE
Playback via SOX

### ISSUE THREAD

**Issue by mg360** [th0ma5w/rtl_fm_python#7]
Hi,
Thanks for making this as it seems to be exactly what I need.  I am a bit of Raspberry pi half wit and can only make my audio output on the Pi DAC hat work when I play back via sox's.  Aplay dodes not work for me.

Is there a way to change the code to output to SOX?  I sort of noctied in the code comments that it is mentioned but that was as far as I got.

**Comment by th0ma5w** [comment]
The author of rtl_fm provides some guidance on his site at http://kmkeen.com/rtl-demod-guide/ ... I think by invoking sox using the "play" command some flags or other settings are inferred. He also lists sox directly to do some fancy network stuff. Personally, I haven't had much luck with sox, but I also haven't tried it much. The help message mentions aplay so I've mostly used that. 

Would you be able to try out some of those examples on that site and let me know how it works out for you? Thank you!!

**Comment by mg360** [comment]
Hi - Thanks for getting back to me. 

These were my findings:
You can use SOX with the following command:
python rtl_fm_python_web.py -M wbfm -f 106.5M | play -r 32k -t raw -e s -b 16 -c 1 -V1 -

Crticial thing is the "-r 32k" after the "play".  This must match the sampling rate that is implied with "-M wmbfm" ie it is sampling at 32k.

**Comment by th0ma5w** [comment]
Cool cool, glad you got something working! Take care -t
