### ISSUE TITLE
compile on windows

### ISSUE THREAD

**Issue by Mitchell1314** [th0ma5w/rtl_fm_python#8]
Truely sorry for this. But I really don't know how to compile it on windows. How can I do "./build.sh"?

**Comment by th0ma5w** [comment]
Well, it is not difficult, but it does involve many steps. If you haven't done compilation of source distributions on Linux or done some Windows development, I might not recommend it as it can be a time suck of googling weird error messages.

There are some details also here: https://github.com/th0ma5w/rtl_fm_python/issues/4

At a high level, what worked for me was:

1. Have a working Cygwin environment with dev tools
2. Compile librtlsdr as appropriate in a Cygwin environment. This is much like it is on Linux with the use of libusb.
3. If all of the above works, the build.sh script should (in theory) just work.

Let me know if you decide to do this or not. Another option may be to use a Linux distro within Virtualbox and using USB pass through, although USB performance inside of a VM may be subpar. Also, in theory, a Docker script could be created that installs everything, and then when ran everything "just works" ... That being said, experimenting with RTLSDR software development projects in general may work a little better in Linux.  

If you decide not to do this, I'll close the issue. If you decide to go forward, I'll try to help as best as I can with what time I have. The holidays are coming up, so I may be unavailable for several days or weeks :P

**Comment by th0ma5w** [comment]
Let me know how this works out for you.
